### ISSUE TITLE
How to support custom login method ?

### ISSUE THREAD

**Issue by bug249286** [kschingiz/artillery-engine-meteor#1]
How to support custom login method name ? 
Thanks.

**Comment by kschingiz** [comment]
Hi, @bug249286 could you please explain how your login method works?
If it's plain Meteor.call, then you could do something like:
```yml
      - call:
          name: "my custom login method"
          payload:
            - login: "login"
              password: "pass"
```
